import { configureStore } from "@reduxjs/toolkit";
import accountReducer from "../features/account/accountSlice";
import budgetReducer from "../features/budget/budgetSlice";
import { backMonth, getTodayString } from "../utils/helpers";
import { v4 as uuid } from "uuid";

const preloadedState = {
  account: {
    name: "My account",
    currentBalance: 11711.4,
    transactions: [
      {
        id: uuid(),
        date: getTodayString("1"),
        payee: "Starting Balance",
        budgetId: "readyToAssign",
        memo: "",
        cashFlow: "inflow",
        amount: 3000,
      },
      {
        id: uuid(),
        date: getTodayString("2"),
        payee: "M&S",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 32.5,
        memo: "Food and drink",
      },
      {
        id: uuid(),
        date: getTodayString("2"),
        payee: "PureGym",
        budgetId: "8",
        cashFlow: "outflow",
        amount: 9,
        memo: "",
      },
      {
        id: uuid(),
        date: getTodayString("3"),
        payee: "EE",
        budgetId: "11",
        cashFlow: "outflow",
        amount: 10,
        memo: "",
      },
      {
        id: uuid(),
        date: getTodayString("5"),
        payee: "KFC",
        budgetId: "4",
        cashFlow: "outflow",
        amount: 18.4,
        memo: "",
      },
      {
        id: uuid(),
        date: getTodayString("5"),
        payee: "Tesco",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 55.2,
        memo: "Weekly shopping",
      },
      {
        id: uuid(),
        date: getTodayString("6"),
        payee: "Connells",
        budgetId: "1",
        cashFlow: "outflow",
        amount: 800,
        memo: "",
      },
      {
        id: uuid(),
        date: getTodayString("8"),
        payee: "Uniqlo",
        budgetId: "6",
        cashFlow: "inflow",
        amount: 22.8,
        memo: "Uniqlo refund",
      },
      {
        id: uuid(),
        date: getTodayString("10"),
        payee: "AXA",
        budgetId: "12",
        cashFlow: "outflow",
        amount: 40,
        memo: "Car insurance",
      },
      {
        id: uuid(),
        date: getTodayString("11"),
        payee: "Costa",
        budgetId: "4",
        cashFlow: "outflow",
        amount: 5.6,
        memo: "",
      },
      {
        id: uuid(),
        date: getTodayString("11"),
        payee: "Morrisons",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 50.2,
        memo: "Weekly shopping",
      },
      {
        id: uuid(),
        date: getTodayString("15"),
        payee: "Octopus",
        budgetId: "2",
        cashFlow: "outflow",
        amount: 102.6,
        memo: "Electricity and gas",
      },
      {
        id: uuid(),
        date: getTodayString("16"),
        payee: "PureGym",
        budgetId: "8",
        cashFlow: "outflow",
        amount: 9,
        memo: "",
      },
      {
        id: uuid(),
        date: getTodayString("18"),
        payee: "Zara",
        budgetId: "6",
        cashFlow: "outflow",
        amount: 14.5,
        memo: "T-shirt",
      },
      {
        id: uuid(),
        date: getTodayString("20"),
        payee: "PureGym",
        budgetId: "8",
        cashFlow: "outflow",
        amount: 9,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(1, "1"),
        payee: "Starting Balance",
        budgetId: "readyToAssign",
        memo: "",
        cashFlow: "inflow",
        amount: 2820,
      },
      {
        id: uuid(),
        date: backMonth(1, "3"),
        payee: "EE",
        budgetId: "11",
        cashFlow: "outflow",
        amount: 10,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(1, "5"),
        payee: "Sainsbury's",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 74.6,
        memo: "Food and drink",
      },
      {
        id: uuid(),
        date: backMonth(1, "7"),
        payee: "PureGym",
        budgetId: "8",
        cashFlow: "outflow",
        amount: 9,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(1, "10"),
        payee: "Nara Thai",
        budgetId: "4",
        cashFlow: "outflow",
        amount: 42.4,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(1, "16"),
        payee: "Tesco",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 51.8,
        memo: "Weekly shopping",
      },
      {
        id: uuid(),
        date: backMonth(1, "19"),
        payee: "Starbucks",
        budgetId: "4",
        cashFlow: "outflow",
        amount: 7.6,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(1, "22"),
        payee: "Morrisons",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 63.2,
        memo: "Weekly shopping",
      },
      {
        id: uuid(),
        date: backMonth(1, "27"),
        payee: "Anglian Water",
        budgetId: "2",
        cashFlow: "outflow",
        amount: 56.7,
        memo: "Water",
      },
      {
        id: uuid(),
        date: backMonth(2, "1"),
        payee: "Starting Balance",
        budgetId: "readyToAssign",
        memo: "",
        cashFlow: "inflow",
        amount: 2980,
      },
      {
        id: uuid(),
        date: backMonth(2, "3"),
        payee: "BBC",
        budgetId: "13",
        cashFlow: "outflow",
        amount: 112.5,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(2, "4"),
        payee: "PureGym",
        budgetId: "8",
        cashFlow: "outflow",
        amount: 9,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(2, "11"),
        payee: "EE",
        budgetId: "11",
        cashFlow: "outflow",
        amount: 10,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(2, "18"),
        payee: "Tesco",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 77.2,
        memo: "Weekly shopping",
      },
      {
        id: uuid(),
        date: backMonth(2, "22"),
        payee: "AXA",
        budgetId: "12",
        cashFlow: "outflow",
        amount: 40,
        memo: "Car insurance",
      },
      {
        id: uuid(),
        date: backMonth(2, "24"),
        payee: "TFL",
        budgetId: "15",
        cashFlow: "outflow",
        amount: 22.9,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(3, "1"),
        payee: "Starting Balance",
        budgetId: "readyToAssign",
        memo: "",
        cashFlow: "inflow",
        amount: 3053,
      },

      {
        id: uuid(),
        date: backMonth(3, "5"),
        payee: "Weekday",
        budgetId: "6",
        cashFlow: "outflow",
        amount: 14.5,
        memo: "Jeans",
      },
      {
        id: uuid(),
        date: backMonth(3, "5"),
        payee: "M&S",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 18.2,
        memo: "Food and drink",
      },
      {
        id: uuid(),
        date: backMonth(3, "6"),
        payee: "PureGym",
        budgetId: "8",
        cashFlow: "outflow",
        amount: 9,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(3, "16"),
        payee: "Morrisons",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 52.3,
        memo: "Weekly shopping",
      },
      {
        id: uuid(),
        date: backMonth(3, "18"),
        payee: "AXA",
        budgetId: "12",
        cashFlow: "outflow",
        amount: 40,
        memo: "Car insurance",
      },
      {
        id: uuid(),
        date: backMonth(3, "20"),
        payee: "Costa",
        budgetId: "4",
        cashFlow: "outflow",
        amount: 10.6,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(3, "24"),
        payee: "Morrisons",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 69.2,
        memo: "Weekly shopping",
      },
      {
        id: uuid(),
        date: backMonth(3, "28"),
        payee: "Octopus",
        budgetId: "2",
        cashFlow: "outflow",
        amount: 92.7,
        memo: "Electricity and gas",
      },
      {
        id: uuid(),
        date: backMonth(4, "1"),
        payee: "Starting Balance",
        budgetId: "readyToAssign",
        memo: "",
        cashFlow: "inflow",
        amount: 2880,
      },
      {
        id: uuid(),
        date: backMonth(4, "2"),
        payee: "Connells",
        budgetId: "1",
        cashFlow: "outflow",
        amount: 780,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(4, "5"),
        payee: "Shell",
        budgetId: "7",
        cashFlow: "outflow",
        amount: 68.4,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(4, "5"),
        payee: "Tesco",
        budgetId: "3",
        cashFlow: "outflow",
        amount: 48.2,
        memo: "Weekly shopping",
      },
      {
        id: uuid(),
        date: backMonth(4, "8"),
        payee: "Apple music",
        budgetId: "9",
        cashFlow: "outflow",
        amount: 10,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(4, "11"),
        payee: "Nando's",
        budgetId: "4",
        cashFlow: "outflow",
        amount: 42.8,
        memo: "",
      },
      {
        id: uuid(),
        date: backMonth(4, "17"),
        payee: "AXA",
        budgetId: "12",
        cashFlow: "outflow",
        amount: 40,
        memo: "Car insurance",
      },
      {
        id: uuid(),
        date: backMonth(4, "25"),
        payee: "Costa",
        budgetId: "4",
        cashFlow: "outflow",
        amount: 5.6,
        memo: "",
      },
    ],
  },
  budget: {
    readyToAssign: 3000,
    budgets: [
      {
        id: "1",
        category: "🏠 Rent",
        assigned: 800,
        activity: -800,
        target: 800,
      },
      {
        id: "2",
        category: "🔌 Utilities",
        assigned: 150,
        activity: -102.6,
        target: 0,
      },
      {
        id: "3",
        category: "🛒 Groceries",
        assigned: 210,
        activity: -137.9,
        target: 260,
      },
      {
        id: "4",
        category: "🍽 Dining out",
        assigned: 60,
        activity: -24,
        target: 60,
      },
      {
        id: "5",
        category: "🕹 Entertainment",
        assigned: 10,
        activity: 0,
        target: 30,
      },
      {
        id: "6",
        category: "👗 Clothing",
        assigned: 50,
        activity: 8.3,
        target: 50,
      },
      {
        id: "7",
        category: "⛽ Gas",
        assigned: 0,
        activity: 0,
        target: 0,
      },
      {
        id: "8",
        category: "🥊 Fitness",
        assigned: 18,
        activity: -27,
        target: 18,
      },
      {
        id: "9",
        category: "🎧 Music",
        assigned: 10,
        activity: 0,
        target: 10,
      },
      {
        id: "10",
        category: "🏖 Vacation",
        assigned: 0,
        activity: 0,
        target: 500,
      },
      {
        id: "11",
        category: "💻 Internet",
        assigned: 10,
        activity: -10,
        target: 10,
      },
      {
        id: "12",
        category: "📄 Insurance",
        assigned: 40,
        activity: -40,
        target: 40,
      },
      {
        id: "13",
        category: "📺 TV streaming",
        assigned: 12,
        activity: 0,
        target: 0,
      },
      {
        id: "14",
        category: "📱 Cell phone",
        assigned: 0,
        activity: 0,
        target: 0,
      },
      {
        id: "15",
        category: "🚇 Transportation",
        assigned: 50,
        activity: 0,
        target: 0,
      },
    ],
  },
};

export default configureStore({
  reducer: {
    account: accountReducer,
    budget: budgetReducer,
  },
  preloadedState,
});
